development:
  adapter:  postgresql
  encoding: unicode
  database: calendar_sample_development
  pool:     5

test:
  adapter:  postgresql
  host:     localhost
  encoding: unicode
  database: calendar_sample_test
  pool:     5
